CREATE DATABASE HR

--Person tablosu oluşturma 
CREATE TABLE PERSON (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CODE VARCHAR(50),
    TCNUMBER VARCHAR(50),
    NAME1 VARCHAR(50),
    SURNAME VARCHAR(50),
    GENDER VARCHAR(1),
    BIRTHDATE DATE,
    INDATE DATE,
    OUTDATE DATE,
    DEPARTMENTID INT,
    POSITIONID INT,
    PARENTPOSITIONID INT,
    MANAGERID INT,
    TELNR VARCHAR(15),
    SALARY FLOAT
)

SELECT * FROM HR.dbo.PERSON

INSERT INTO HR.dbo.PERSON(CODE ,TCNUMBER,NAME1,SURNAME,GENDER,BIRTHDATE,INDATE,OUTDATE,DEPARTMENTID,POSITIONID,PARENTPOSITIONID,MANAGERID,TELNR,SALARY)
VALUES('001','1234567801','Ahmet','Yılmaz','E','1980-01-01','2020-01-01',NULL,1,1,NULL,NULL,'05555555555',7000)

INSERT INTO HR.dbo.PERSON(CODE,TCNUMBER,NAME1,SURNAME,GENDER,BIRTHDATE,INDATE,OUTDATE,DEPARTMENTID,POSITIONID,PARENTPOSITIONID,MANAGERID,TELNR,SALARY)
VALUES('002','1234567802','Ayşe','Kara','K','1985-05-05','2021-02-01',NULL,2,2,NULL,1,'05555555556',5000)

INSERT INTO HR.dbo.PERSON(CODE,TCNUMBER,NAME1,SURNAME,GENDER,BIRTHDATE,INDATE,OUTDATE,DEPARTMENTID,POSITIONID,PARENTPOSITIONID,MANAGERID,TELNR,SALARY)
VALUES('003','1234567803','Mehmet','Çelik','E','1990-03-03','2019-03-01','2021-12-31',3,3,NULL,1,'05555555557',6000)

--DEPARTMENT TABLOSUNU OLUŞTURMA
CREATE TABLE DEPARTMENT(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DEPARTMENT VARCHAR(50)
    ) 

SELECT * FROM DEPARTMENT

INSERT INTO HR.dbo.DEPARTMENT(DEPARTMENT)VALUES('Muhasebe') 
INSERT INTO HR.dbo.DEPARTMENT(DEPARTMENT)VALUES('İnsan Kaynakları') 
INSERT INTO HR.dbo.DEPARTMENT(DEPARTMENT)VALUES('IT') 


--Position tablosunu oluşturma
CREATE TABLE POSITION(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    POSITION VARCHAR(50)
)

SELECT * FROM HR.dbo.[POSITION]

INSERT INTO  HR.dbo.[POSITION] (POSITION)VALUES('Müdür')
INSERT INTO HR.dbo.[POSITION]  (POSITION)VALUES('Yardımcı')
INSERT INTO  HR.dbo.[POSITION] (POSITION)VALUES('Uzman')


--OUTDATE'İ NULL OLAN KİŞİLERİ SORGULAMA
SELECT *
FROM HR.DBO.PERSON
WHERE OUTDATE IS NULL

--HER DEPARTMANDA ÇALIŞSAN KİŞİ SAYISI
SELECT *
FROM HR.DBO.PERSON
SELECT *
FROM HR.DBO.DEPARTMENT
SELECT *
FROM HR.DBO.[POSITION]


INSERT INTO HR.dbo.PERSON(CODE,TCNUMBER,NAME1,SURNAME,GENDER,BIRTHDATE,INDATE,OUTDATE,DEPARTMENTID,POSITIONID,PARENTPOSITIONID,MANAGERID,TELNR,SALARY)
VALUES('004','1234567804','Emre','Yıldırım','E','1990-04-04','2019-04-02','2021-11-11',3,3,NULL,1,'05555555558',3000)

SELECT D.DEPARTMENT ,COUNT(P.ID)
FROM HR.DBO.PERSON P
INNER JOIN HR.DBO.DEPARTMENT D 
ON  P.DEPARTMENTID = D.ID
GROUP BY D.DEPARTMENT

--Cinsiyete ve departmana göre çalışan sayısı
SELECT P.GENDER ,P.SURNAME
FROM HR.DBO.PERSON P
GROUP BY P.GENDER,P.SURNAME

SELECT P.GENDER, D.DEPARTMENT ,COUNT(*)
FROM HR.DBO.PERSON P
INNER JOIN HR.DBO.DEPARTMENT D 
ON  P.DEPARTMENTID = D.ID
GROUP BY D.DEPARTMENT,P.GENDER

-- Belirli bir pozisyonda çalışanların maaş istatistikleri

SELECT PO.POSITION, AVG(P.SALARY)
FROM HR.dbo.[POSITION] PO
INNER JOIN HR.dbo.[PERSON] P
ON PO.ID = P.POSITIONID
GROUP BY PO.[POSITION]

SELECT D.DEPARTMENT, MIN(P.SALARY) MINIMUM_MAAS,MAX(P.SALARY) MAX_MAAS,AVG(P.SALARY) ORTALAMA_MAAS
FROM HR.dbo.DEPARTMENT D
INNER JOIN HR.dbo.PERSON P
ON P.DEPARTMENTID=D.ID
GROUP BY D.DEPARTMENT
HAVING D.DEPARTMENT = 'IT'  

--Pozisyonlara göre kişi sayısı ve ortalama maaş
SELECT  PO.POSITION, COUNT(*) KISI_SAYISI,ROUND(AVG(P.SALARY),0) ORTALAMA_MAAS
FROM HR.dbo.[POSITION] PO
INNER JOIN HR.dbo.PERSON P
ON  P.POSITIONID = PO.ID
GROUP BY PO.POSITION
 
-- Cinsiyete göre giriş yılı ve kişi sayısı
SELECT * FROM HR.dbo.PERSON

SELECT P.GENDER,COUNT(*) KISI_SAYISI,DATEPART(YEAR,INDATE) GIRIS_YILI
FROM HR.dbo.PERSON P
GROUP BY P.GENDER,DATEPART(YEAR,INDATE)

-- Ortalama maaşın 5500'den fazla olduğu departmanlar
SELECT D.DEPARTMENT,AVG(P.SALARY) ORTALAMA_MAAS_5500DEN_BUYUK
FROM HR.dbo.PERSON P
INNER JOIN HR.dbo.DEPARTMENT D
ON P.DEPARTMENTID = D.ID
GROUP BY D.DEPARTMENT
HAVING AVG(P.SALARY) > 5500

-- Departmanlara göre ortalama çalışma süresi
SELECT  
DEPARTMENT,ROUND(AVG(WORKINGTIME),0) AS AVG_WORKING_TIME
            
FROM (SELECT 
                D.DEPARTMENT,
                    CASE
                        WHEN P.OUTDATE IS NOT NULL THEN DATEDIFF(MONTH ,P.INDATE,P.OUTDATE) 
                        ELSE DATEDIFF(MONTH ,INDATE,GETDATE()) 
                    END AS WORKINGTIME
                FROM HR.dbo.PERSON P
                JOIN HR.dbo.DEPARTMENT D 
                ON D.ID = P.DEPARTMENTID)T
GROUP BY DEPARTMENT
ORDER BY AVG_WORKING_TIME DESC




-- CRUD
----------------------
----------------------


-- PERSON tablosuna yeni bir sütun eklemek: Email

ALTER TABLE HR.dbo.PERSON
ADD Email  VARCHAR(12)

SELECT *FROM HR.dbo.PERSON

-- ID'si 1 olan kişinin maaşını ve email adresini güncellemek
UPDATE HR.dbo.PERSON 
SET SALARY = 8000 ,
     Email = 'e@yandex.com'
WHERE ID=1 

-- Tüm personelin telefon numarasını güncellemek

UPDATE HR.dbo.PERSON
SET TELNR='444444'

-- PERSON tablosuna Status sütunu ekleme ve varsayılan değer ayarlama
ALTER TABLE HR.dbo.PERSON
ADD Status VARCHAR(10) NOT NULL DEFAULT'Aktif'

-- OUTDATE belirlenmiş kişilerin durumunu Pasif olarak güncelleme
UPDATE HR.dbo.PERSON
SET Status = 'Pasif'
WHERE OUTDATE  IS NOT NULL

-- 30 yaşından büyük kişilerin maaşına %10 zam yapma
UPDATE HR.dbo.PERSON
SET SALARY = SALARY*1.1
WHERE YEAR(GETDATE()) - YEAR(BIRTHDATE) > 30